const nursesData = [
    {
      id: '1',
      name: 'Maria Silva',
      formation: 'Enfermagem',
      specialization: 'Curativos',
      description: 'Especialista em cuidados com feridas e curativos complexos. Realiza procedimentos avançados para tratamento de feridas, garantindo a recuperação eficaz e o conforto do paciente. Experiência em diferentes tipos de curativos e técnicas para promover a cicatrização.',
      tags: ['Curativos', 'Injeções', 'Vacinas', 'Cuidados Semanais'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '2',
      name: 'João Souza',
      formation: 'Enfermagem',
      specialization: 'Injeções',
      description: 'Experiência em administração de medicamentos e vacinas, com foco na precisão e segurança. Realiza injeções intramusculares, subcutâneas e intravenosas, além de monitorar e documentar as reações dos pacientes. Cuida de pacientes com necessidades específicas de medicação.',
      tags: ['Injeções', 'Vacinas', 'Acompanhamento'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '3',
      name: 'Alice Gomes',
      formation: 'Enfermagem',
      specialization: 'Sondas',
      description: ' Experiência em administração e manejo de sondas, incluindo sondas nasogástricas e vesicais. Realiza procedimentos para garantir a manutenção adequada e o conforto do paciente. Também especializada em injeções e curativos, oferecendo um cuidado abrangente.',
      tags: ['Sondas', 'Injeções', 'Vacinas', 'Curativos'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '4',
      name: 'Carla Pereira',
      formation: 'Terapia Ocupacional',
      specialization: 'Reabilitação Física',
      description: 'Ajuda pacientes a recuperar habilidades para realizar atividades diárias após lesões ou doenças. Trabalha com pacientes para melhorar a coordenação, força e habilidades motoras. Utiliza técnicas terapêuticas para promover a independência e a qualidade de vida.',
      tags: ['Reabilitação', 'Atividades Diárias', 'Apoio'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '5',
      name: 'Fernanda Costa',
      formation: 'Fisioterapia',
      specialization: 'Reabilitação Pós-Cirúrgica',
      description: 'Especialista em reabilitação física após cirurgias ortopédicas e neurológicas. Elabora e aplica programas de exercícios para promover a recuperação completa e a restauração da mobilidade. Acompanha o progresso do paciente e ajusta os tratamentos conforme necessário.',
      tags: ['Fisioterapia', 'Reabilitação', 'Exercícios'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '6',
      name: 'Lucas Almeida',
      formation: 'Fonoaudiologia',
      specialization: 'Tratamento de Disfagia',
      description: 'Experiência no tratamento de dificuldades de deglutição e distúrbios da fala. Realiza avaliações detalhadas e desenvolve planos de tratamento personalizados. Trabalha para melhorar a comunicação e a segurança alimentar dos pacientes.',
      tags: ['Disfagia', 'Fala', 'Comunicação'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '7',
      name: 'Paula Martins',
      formation: 'Cuidadora de Idosos',
      specialization: 'Assistência Domiciliar',
      description: 'Proporciona cuidados e apoio diário para idosos, incluindo auxílio em atividades diárias como alimentação e higiene. Garante o bem-estar geral dos pacientes, oferecendo companhia e suporte emocional. Experiência em lidar com diversas necessidades de cuidados.',
      tags: ['Assistência Domiciliar', 'Idosos', 'Apoio Diário'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '8',
      name: 'Cláudia Rodrigues',
      formation: 'Técnico de Enfermagem',
      specialization: 'Cuidados Gerais',
      description: 'Oferece suporte e cuidados gerais em ambientes domiciliares e instituições de saúde. Realiza monitoramento de sinais vitais, administração de medicamentos e assistência em atividades diárias. Experiência em atender a diferentes perfis de pacientes e suas necessidades.',
      tags: ['Cuidados Gerais', 'Suporte', 'Ambientes Domiciliares'],
      photo: 'https://via.placeholder.com/150',
    },
    {
      id: '9',
      name: 'Eduarda Martins',
      formation: 'Psicologia',
      specialization: 'Apoio a Pacientes com Mobilidade Reduzida',
      description: 'Oferece suporte psicológico contínuo para pacientes com dificuldades de mobilidade ou em tratamento prolongado em casa. Trabalha para melhorar o bem-estar emocional e ajustar o suporte psicológico às necessidades individuais dos pacientes. Auxilia na adaptação ao ambiente domiciliar e no enfrentamento das limitações.',
      tags: ['Psicologia', 'Mobilidade Reduzida', 'Apoio Emocional', 'Tratamento Domiciliar'],
      photo: 'https://via.placeholder.com/150',
    },  
    {
      id: '10',
      name: 'Roberta Lima',
      formation: 'Cuidadora de Idosos',
      specialization: 'Assistência Domiciliar',
      description: 'Proporciona cuidados e apoio diário para idosos, incluindo auxílio em atividades diárias como alimentação, mobilidade e higiene pessoal. Foca na promoção do conforto e bem-estar do paciente, oferecendo companhia e suporte emocional. Experiência em criar um ambiente seguro e acolhedor em casa, garantindo uma assistência completa e atenciosa.',
      tags: ['Assistência Domiciliar', 'Idosos', 'Apoio Diário'],
      photo: 'https://via.placeholder.com/150',
    },
  
  ];
  
  export default nursesData;
  